spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: ecommerce
server:
  port: 9090

CLOUDINARY_URL: cloudinary://411523671333719:Q17YefKj9u3DNXyUMw-g8TbdZ5U@dr1kmw1w4
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  
